### ISSUE TITLE
start versionin the libraries

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#129]
- we still have soname 0.0.1 and already ran into a few problems when changing API/ABI and not changing the soname

**Comment by xsuchy** [comment]
we have versioned soname nowadays.

**Comment by ernestask** [comment]
That’s not what the issue is about. The original comment already states that we use 0.0.1.

**Comment by ernestask** [comment]
Every other release we do breaks binary compatibility and we still ship libreport.so.0.

**Comment by xsuchy** [comment]
Resolved in https://github.com/abrt/libreport/pull/635
