### ISSUE TITLE
make it more clear how to report to scp

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#22]
Opened '20110818T08:49:39' by jmoskovc as https://fedorahosted.org/abrt/ticket/331

from rhbz#731258:

The GUI used to have ftp, scp, local, bugzilla
buttons as options, which are very direct and convenient for users. Is there
any plan to update the GUI?

**Comment by xsuchy** [comment]
wontfix. there is issue to rather use ssh instead of scp.
