### ISSUE TITLE
Allowed me to upload an incomplete trace(?)

### ISSUE THREAD

**Issue by AdamWill** [abrt/libreport#261]
I was trying to file a crash a couple of days ago, and remote retracing failed (it seems to fail almost all the time on Rawhide recently). abrt prompted me to download like 2GB to do the local retrace, I didn't have time/space for that, so I clicked cancel...and then it went right ahead and let me file the bug anyway!

The resulting report is https://bugzilla.redhat.com/show_bug.cgi?id=1092704

it can't be right that it needed 2GB of debuginfo, _but_ the bug report was valid without it. Either the debuginfo wasn't needed, or it shouldn't have sent the report.

**Comment by xsuchy** [comment]
It would be a lot of work for just little gain. The chance that really do not need any of neew debuginfo is pretty low. Closing.
