### ISSUE TITLE
Integrate with CentOS's Mantis bug tracker

### ISSUE THREAD

**Issue by mbrysa** [abrt/libreport#272]
Libreport should be able to create bugs in CentOS's Mantis the same way it creates bugzillas for Fedora/RHEL.
Web: http://bugs.centos.org/
SOAP API: https://bugs.centos.org/api/soap/mantisconnect.php?wsdl
Python SOAP API example using suds:
```
from suds.client import Client
url = "https://bugs.centos.org/api/soap/mantisconnect.php?wsdl"
client = Client(url)
bug_id = 1234
result = client.service.mc_issue_get("username", "password", 1234)
```

**Comment by jfilak** [comment]
ABRT users on CentOS-7 can report to bugs.centos.org so I consider this issue fixed.
