### ISSUE TITLE
Add a workflow for CentOS

### ISSUE THREAD

**Issue by jfilak** [abrt/libreport#304]
1. submit a uReport to ABRT server
2. generate backtrace on a local machine
3. add a comment and review data
4. file a bug report in CentOS Bug tracker (full report)
5. attach URL to the full report to the uReport on ABRT server

Blocks #272

**Comment by jfilak** [comment]
I would create a new event named **report_CentOSBugTracker** for the full report point mentioned in the description and create a new libreport sub-package shipping the workflow and the event.

**Comment by jfilak** [comment]
Start with the event xml definition (man report-gtk). You can use https://github.com/abrt/libreport/blob/master/src/plugins/report_Bugzilla.xml.in as a template.

**Comment by jfilak** [comment]
You are done when all these steps are possible:
1. yum install libreport-workflow-centos
2. change CentOS Bug Tracker URL to a testing instance
3. submit a coredump, a Python exception, a kernel oops to CentOS Bug Tracker

**Comment by mhabrnal** [comment]
Where to placed a definition of the new event **report_CentOSBugTracker**?
There are two options:

1. All definitions of events are placed in ``abrt/src/plugins`` and there are shipped by abrt* packages. In this case we can placed the definitions to those files. The definitons will be available even if isn't installed package **libreport-workflow-centos**.

2. Placed the definitions to the ``libreport/src/workflofs`` or  ``libreport/src/plugins``. Those definions will be shipped by libreport-workflow-centos package and will be available only if the package  **libreport-workflow-centos** is installed.

Any ideas?

**Comment by jfilak** [comment]
I would start with the second one.
