### ISSUE TITLE
Global configuration (events and reporters)

### ISSUE THREAD

**Issue by jfilak** [abrt/libreport#316]
libreport supports configuration either per event or per plug-in but some of the preferences need to be shared between all libreport tools. **Proxy settings** (#142) are one of those shared configuration options.

libreport configuration sources for the events:
* `/etc/libreport/events/*.conf`
* `/usr/share/libreport/events/*.xml`
* `$HOME/.config/abrt/events/*.conf`
* D-Bus Secret Service

libreport configuration sources for *report-gtk*:
* `/etc/libreport/forbidden_words.conf`
* `/etc/libreport/ignored_words.conf`
* `$HOME/.config/abrt/settings/report-gtk.conf`

libreport configuration sources for *report-cli*:
* `$HOME/.config/abrt/settings/report-cli.conf`

Shared configuration:
* networking
* privacy (always excluded files, scrubbed environment variable names)
* ...

When the global configuration would be used:
* report from *report-gtk*
* report from *report-cli*
* run a custom event (only if the caller wishes it)

Suggestions:
* configuration files: `/etc/libreport/libreport.conf`, `$HOME/.config/abrt/settings/libreport.conf`
* place all configuration options to the global configuration file
* use the current format
* `libreport_load_global_configuration()`, `libreport_free_global_configuration()`: for the custom events mentioned above

Notes:
* `globals.conf` : it looks nice in `/etc/libreport/` but it is a terrible name for a file in `$HOME/.config/abrt/settings/` because users would be confused -> `globals.conf` ? is this file used for ABRT or libreport?

**Comment by mmilata** [comment]
Looks very reasonable to me.

**Comment by jfilak** [comment]
I consider this issue fixed.
