### ISSUE TITLE
create a guide how to write custom events

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#35]
Opened '20111109T13:17:40' by jmoskovc as https://fedorahosted.org/abrt/ticket/364

Started here: https://fedorahosted.org/abrt/wiki/AbrtConfiguration

**Comment by xsuchy** [comment]
https://web.archive.org/web/20160316072517/https://fedorahosted.org/abrt/wiki/AbrtConfiguration

**Comment by xsuchy** [comment]
it is here:
https://abrt.readthedocs.io/en/latest/conf.html#event-configuration
I think we can close this.
