### ISSUE TITLE
Some strings marked for translation concatenate compile-time constants and are thus untranslatable.

### ISSUE THREAD

**Issue by lonemadmax** [abrt/libreport#379]
Found in usage strings in:
`plugins/report.c`
`plugins/reporter-bugzilla.c`
`plugins/reporter-mailx.c`
`plugins/reporter-mantisbt.c`
`plugins/reporter-rhtsupport.c`
`plugins/reporter-upload.c`

in the form of:

``` C
    const char *program_usage_string = _(
    [...]
        "\n""If not specified, CONFFILE defaults to "CONF_DIR"/plugins/upload.conf"
    [...]
    );
```

`CONF_DIR` is not the only symbol, and there may be more cases.

That is extracted to the .po file as:
`"[...]\nIf not specified, CONFFILE defaults to "`

But searched in run-time with the whole string.

Some options:
- Don't mark those strings as translatable.  That would keep them untranslated as they are now, but reduce noise in the message catalog and effort for translators.
- Rewrite the sentences so that no symbols are needed.
- Change the scripts so that when extracting the strings for the `.po` files the symbols are resolved.  That would make the catalog dependent on compile or configure time options, wherever they come from.
- The cases found so far seem to all be strings for `show_usage_and_die`.  So maybe other magic substitutions (like `&`) could be defined for the symbols needed.
- Change `show_usage_and_die` to accept the string and a list of parameters à la `printf`.
- Do the substitution in the callers with `asprintf` or similar.
- Do the printing itself in the callers.  This would also allow for the breaking of long strings into several paragraph-size strings, but it would also move `INITIALIZE_LIBREPORT()` into the caller, if it's needed.
- Whatever the real coders out there come up with.

**Comment by lonemadmax** [comment]
Not all such strings go to `show_usage_and_die`.  In `plugins/reporter-rhtsupport.c` we find:
`       error_msg_and_die(_("Can't create a temporary directory in "LARGE_DATA_TMP_DIR));`
`        errmsg = _("Can't create temporary file in "LARGE_DATA_TMP_DIR);`

**Comment by mzidek-gh** [comment]
This was fixed by: https://github.com/abrt/libreport/pull/692
