### ISSUE TITLE
Don't warn when user config file (word white-/blacklist) doesn't exist

### ISSUE THREAD

**Issue by genodeftest** [abrt/libreport#395]
Currently, when files like `~/.config/abrt/settings/ignored_words.conf` don't exist, libreport gives a warning (see code in `src/lib/user_settings.c:load_words_from_file()` which gets called by src/gui-wizard-gtk/wizard.c)
In my opinion missing these files is expected behaviour and not worth a warning. abrt/libreport should only warn if this file exists AND cannot be opened.

**Comment by jfilak** [comment]
I believe commit 7deb540029bb421274e6885bd34095beb5a120ac fixes this issue.

**Comment by genodeftest** [comment]
No, it doesn't. With libreport 2.7.2 installed, this warning is still present.

As I've written above, this warning is printed from `user_settings.c:load_words_from_file()`, not from `configuration_files.c`.
