### ISSUE TITLE
Sensitive words text box is one pixel tall

### ISSUE THREAD

**Issue by ariscop** [abrt/libreport#407]
Same issue as 18a1e903c35d72cdb2f436237235d70a3a798cf4 i imagine
![screenshot](https://cloud.githubusercontent.com/assets/1522423/13099706/11e17d4e-d589-11e5-8c46-fda017f0fd64.png)

**Comment by mhabrnal** [comment]
Thank you for the report!

The issue should be fixed in version libreport-2.6.4-3.fc24.
