### ISSUE TITLE
packagekit integration

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#42]
Opened '20111205T11:45:26' by jmoskovc as https://fedorahosted.org/abrt/ticket/417
- right now we just show a command which user has to manually run as root
- we should make it easier for users and just add a button (in GUI) or ask (in cli) to call packageKit to do the job
- the good thing is that pkgKit will take care about the authorization (Even shows the dialog if run in X)

**Comment by xsuchy** [comment]
with current state of packagekit, this is not likely to happen.
