### ISSUE TITLE
2.7.0 tarball broken and missing

### ISSUE THREAD

**Issue by glensc** [abrt/libreport#434]
libreport 2.7.0 is 0 byte here https://fedorahosted.org/released/abrt/
and no generated tarball uploaded to github either:
https://github.com/abrt/libreport/releases/tag/2.7.0

**Comment by jfilak** [comment]
I uploaded the tarball to fedorahosted.org, so it should be ok now. However, github generates the 2.7.0 tarball for me without any problems - https://github.com/abrt/libreport/archive/2.7.0.tar.gz.

Thank you for the report and sorry for the inconvenience.

**Comment by glensc** [comment]
the github generated tarball is not the same as tarball produced by `make dist` (it contains only source from git repo). besides lacking all autofoo things, it for example lacks `libreport-version` file, and current `Makefile` rules are broken without that.

**Comment by jfilak** [comment]
> it's a hack.

You have to run `./autogen.sh` before you can run `./configure` and `make`.

I thought running `./autogen.sh` is common task when building from sources but it's true that released tarballs aren't the same as github tarballs.

**Comment by glensc** [comment]
nice projects include generated `configure` and other related generated files in their tarball. `./autogen.sh` should be ran only if you modified any of the configure or automake source files. or if you are project developer.

also, the generated `configure` etc should *not* be included in version system (git).

so the only sane solution is to do `make dist` and upload the resulting tarball. github source tarball contains only source files. but, you can also upload generated tarball to github release page beside the source tarball: https://github.com/abrt/libreport/releases/tag/2.8.0
