### ISSUE TITLE
Allow users to start only the workflows that can be run

### ISSUE THREAD

**Issue by jfilak** [abrt/libreport#443]
Workflow configuration files (e.g. /etc/libreport/workflows.d/report_fedora.conf) contains only the condition line, so we can use the body for any magic we need like ("ping bugzilla.redhat.com").

The return code 0 should mean that the workflow can be run. The output should be used to inform users about problems. 

See: https://bugzilla.redhat.com/show_bug.cgi?id=1214630

**Comment by xsuchy** [comment]
I really do not agree we should implement this. Should we also check that user is on dialup and we should not send big attachment? This can easily become monster. We should not be smarter than user.
