### ISSUE TITLE
Can't build on Manjaro : No package 'libsystemd-journal' found

### ISSUE THREAD

**Issue by Salamandar** [abrt/libreport#450]
Well, I was trying to build the package https://aur.archlinux.org/packages/libreport/ for blivet, and the configure tells me : 

    No package 'libsystemd-journal' found
Okay. So I check which package I have and :
* I have the file `/usr/include/systemd/sd-journal.h`
* I have the pkg-config file `libsystemd` (`cflags="", libs="-lsystemd"`)
* If i modify the ./configure to use not libsystemd-journal but libsystemd, that works, builds and links.

**Comment by jfilak** [comment]
Thank you for the issue. Updating to libreport-2.7.2 should fix it - see commit 7c218fb39d71c9e33e8dbbcc786e968194b30a19.

**Comment by Salamandar** [comment]
Fix confirmed, didn't see the AUR package was on an old release (it's up to date now !) 
Thanks :D
