### ISSUE TITLE
[RFE] src/plugins/bugzilla.conf should default to value from /etc/os-release

### ISSUE THREAD

**Issue by jcpunk** [abrt/libreport#459]
Right now src/plugins/bugzilla.conf is hard coded to use bugzilla.redhat.com.  However, Fedora 20+ and RHEL7 include a bugzilla url in /etc/os-release.

Defaulting to the value set in /etc/os-release allows for easier integration by respins.

**Comment by jfilak** [comment]
Thank you for the issue. It make sense because libreport is already using `/etc/os-release` to get Bugzilla Product and Bugzilla Product Version.
