### ISSUE TITLE
Build fails with Python 3.6

### ISSUE THREAD

**Issue by stratakis** [abrt/libreport#470]
Trying to build libreport in Fedora 26 by using Python 3.6 (in the f26-python3 side tag) I get various test suite failures.

Relevant task: https://koji.fedoraproject.org/koji/taskinfo?taskID=16855910

Bugzilla with more info: https://bugzilla.redhat.com/show_bug.cgi?id=1403949

Currently this is blocking us from building abrt and also (in the chain of dependencies) anaconda as well.

**Comment by jfilak** [comment]
The lz4-decompression test case failure is already fixed in upstream: https://github.com/abrt/libreport/commit/e16dcbbfaa95dbe86cc9a26a78a03e5abf4102eb

**Comment by jfilak** [comment]
Commit https://github.com/abrt/libreport/commit/b002bf17afd60585acbfaf728449125eb9379647 fixes the problem_report test case.
