### ISSUE TITLE
coverity: review outstanding issues for libreport

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#50]
Opened '20120309T13:48:59' by rmarko as https://fedorahosted.org/abrt/ticket/480

All the issues need to be reviewed and classified so we are able to track new issues easily.

**Comment by xsuchy** [comment]
no need to create issue to handle anothers issues.... :)

**Comment by mozeq** [comment]
I believe that this ticket was here as a reminder to go and check the
coverity logs and turn the reported problems into real tickets, so we can
pull them into the sprint.

2017-05-11 8:53 GMT+01:00 Miroslav Suchý <notifications@github.com>:
