### ISSUE TITLE
dupe detection doesn't work even if the hash is the same

### ISSUE THREAD

**Issue by mozeq** [abrt/libreport#52]
Opened '20120321T13:30:30' by jmoskovc as https://fedorahosted.org/abrt/ticket/492

What about bugs that your script did not catch?

Bug 752238[1] has about 100 dupes against it that I just wore out
after a handful of setting DUPLICATE by hand. I set the dupes to bug
734442[2] before I realized 752238[1] had more CCs.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=752238
[2] https://bugzilla.redhat.com/show_bug.cgi?id=734442

**Comment by xsuchy** [comment]
This is old. We need some new case.
