### ISSUE TITLE
What is this thing trying to say?

### ISSUE THREAD

**Issue by elad661** [abrt/libreport#561]
I'm sorry for the non descriptive bug title, but I'm completely baffled by this UI.

Can you explain what is going on here and why does it look like this? What are you trying to achieve by showing this? What does copyright have to do with a list of python exceptions?
![screenshot from 2014-08-25 01 08 30](https://cloud.githubusercontent.com/assets/498903/4024850/af4899d0-2bdc-11e4-8351-1f6fed0b4e53.png)

(disregard the actual backtrace, it's a bug I used for testing the reporting process)

**Comment by xsuchy** [comment]
Closing as duplicate of https://github.com/abrt/libreport/issues/312
