### ISSUE TITLE
abrt-cli list seems to mix up older existing crash reports (time and directory not matching)

### ISSUE THREAD

**Issue by captainjs** [abrt/libreport#603]
Hi,
We run RHEL7.7, 
abrt-x86_64 2.1.11-55-el7.

abrt-cli list seems to mix up older existing crash reports (time and directory not matching)

See, pay attention to this:
time:    
Directory:

[root@hostname ~]# abrt-cli list
id 03116fc3ab8a3572fb9483aee2873ce4e663f172
reason:         abrt-harvest-vmcore:252:harvest_vmcore:TypeError: delete_and_close() takes exactly 2 arguments (1 given)
time:           Tue 25 Feb 2020 09:58:41 AM CET
cmdline:        /usr/bin/python /usr/sbin/abrt-harvest-vmcore
package:        abrt-addon-vmcore-2.1.11-55.el7
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/Python-2020-02-25-09:58:41-3915
Run 'abrt-cli report /var/spool/abrt/Python-2020-02-25-09:58:41-3915' for creating a case in Red Hat Customer Portal

id 91691908307fed583e0186a30c243350658400ca
**time:**           Tue 25 Feb 2020 09:57:28 AM CET
uid:            0
Directory:      /var/spool/abrt/vmcore-127.0.0.1-2019-04-21-01:07:01.new
Run 'abrt-cli report /var/spool/abrt/vmcore-127.0.0.1-**2019-04-21-**01:07:01.new' for creating a case in Red Hat Customer Portal

The Autoreporting feature is disabled. Please consider enabling it by issuing
'abrt-auto-reporting enabled' as a user with root privileges
[root@hostame ~]# date
Tue Feb 25 10:45:26 CET 2020

I have verified, the file in question in /var/crash is actually really from 2019, I could see in the vmcore-dmesg some references to old kernel. Also, I did a ls -lrta of the folder and it all indicates 2019.

FYI, it seems that the issue is related to the presence of these files:

[root@hostname 127.0.0.1-2019-04-21-01:07:01]# pwd
/var/crash/127.0.0.1-2019-04-21-01:07:01
[root@hostname 127.0.0.1-2019-04-21-01:07:01]# ls -lrta
total 3801144
-rw-r--r--. 1 root root    1062268 Apr 21  2019 vmcore-dmesg.txt
-rw-------. 1 root root 3891301027 Apr 21  2019 vmcoreBKP25022020
drwxr-xr-x. 3 root root         43 Feb 25 11:36 ..
drwxr-xr-x. 2 root root         55 Feb 25 11:37 .
[root@hostname 127.0.0.1-2019-04-21-01:07:01]# date
Tue Feb 25 16:31:24 CET 2020

FYI, it appears that there is something wrong with that vmcore file. It was named vmcore, but I can not copy it, I cannot download it. I could rename it from vmcore to this vmcoreBKP25022020.

[root@hostname 127.0.0.1-2019-04-21-01:07:01]# lsattr vmcoreBKP25022020
lsattr: Operation not permitted While reading flags on vmcoreBKP25022020
[root@hostname 127.0.0.1-2019-04-21-01:07:01]# ls -lrta vmcoreBKP25022020
-rw-------. 1 root root 3891301027 Apr 21  2019 vmcoreBKP25022020
[root@hostname 127.0.0.1-2019-04-21-01:07:01]# date
Tue Feb 25 16:34:00 CET 2020

If you need the files abrt created, it's in Red Hat support case 02542116 (25Feb2020ch-sw01-i54x-06.zip)

Cheers.

**Comment by ernestask** [comment]
This belongs on the Red Hat Bugzilla.
