### ISSUE TITLE
I get 13 emails on every new abrt reported bugzilla, please make it 1

### ISSUE THREAD

**Issue by hroncok** [abrt/libreport#619]
![_](https://user-images.githubusercontent.com/2401856/79618965-c6505c00-810b-11ea-8a5d-f9cb2ea6e93a.png)

I think this was already discussed at least once but I cannot find it. I always thought this was fixed in abrt, but users report bugs trough an old unfixed abrt version. However the reports are from Fedora 32.

Please, mark all the attachment changes in buzgillas as "This is a minor update (do not send email)". Thank you.

**Comment by ernestask** [comment]
Per the documentation, it only works if the user is in the group specified in `minor_update_group`. Could be that only Fedora contributors or Red Hat employees have the ability.

**Comment by hroncok** [comment]
I don't normally receive minor update emails. Hence I belive those are not set as minor. I'm both Red Hat employee and Fedora packager.

**Comment by hroncok** [comment]
> We already do that.

Well, in that case, something is broken. Can you point me to the code that does that?

**Comment by hroncok** [comment]
The minor_update_group membership is based on my user settings in https://bugzilla.redhat.com/userprefs.cgi?tab=email

![_](https://user-images.githubusercontent.com/2401856/79633049-4ce45800-8163-11ea-9b6f-bf2eb66a8db0.png)

**Comment by ernestask** [comment]
The specific bit is https://github.com/abrt/libreport/blob/364b3fd95134737536b0f8d764ddee20b29df756/src/plugins/rhbz.c#L633.

**Comment by hroncok** [comment]
Oh, I remember https://github.com/abrt/libreport/pull/547 now, thanks.

Looks like something changed again?

**Comment by ernestask** [comment]
> The minor_update_group membership is based on my user settings in https://bugzilla.redhat.com/userprefs.cgi?tab=email

Are you sure that’s not `wants_bug_mail`? `minor_update_group` is for senders, not receivers.

**Comment by hroncok** [comment]
So if the bugzilla reporter is not in the `minor_update_group`, ABRT cannot use the feature with that user?

**Comment by ernestask** [comment]
Bingo. Looking at the code for the Red Hat instance, if the `can_minor_update` bit is not specifically set for the user, it checks if the user is either in the `admin` or `minor_update_group` groups.

Might be related to https://bugzilla.redhat.com/show_bug.cgi?id=1708003; I’ll try to poke around in the database.

**Comment by hroncok** [comment]
I've been just reading the https://bugzilla.redhat.com/show_bug.cgi?id=1708003 thing, but I am unsure if I understand this right. I don't see any reason to restrict users to send minor updates :(

Thanks for looking into it and sorry for the confusion.

**Comment by ernestask** [comment]
The outcome of that bug was that `minor_update_group` was changed from `editbugs` to `community`. I can only see `fedora_contrib` granting membership to `community` (and `redhat` to `fedora_contrib`), so it would follow that this only works for Fedora contributors. My familiarity with Bugzilla isn’t stellar, but this seems to make sense to me.

Have you observed that the flag *sometimes* works? I would otherwise try a little experiment to see if that is indeed the case.

**Comment by ernestask** [comment]
If so, then I would probably move the discussion to Bugzilla and see what Jeff thinks.

**Comment by hroncok** [comment]
> Have you observed that the flag sometimes works?

As far as my bugzilla email history goes, it never works. But my bugzilla email history unfortunately only goes back coule weeks as I prune it regularly.

https://bugzilla.redhat.com/show_bug.cgi?id=1825412
https://bugzilla.redhat.com/show_bug.cgi?id=1825057
https://bugzilla.redhat.com/show_bug.cgi?id=1824405
https://bugzilla.redhat.com/show_bug.cgi?id=1824001
https://bugzilla.redhat.com/show_bug.cgi?id=1823119
https://bugzilla.redhat.com/show_bug.cgi?id=1823189
https://bugzilla.redhat.com/show_bug.cgi?id=1823096
https://bugzilla.redhat.com/show_bug.cgi?id=1821428
https://bugzilla.redhat.com/show_bug.cgi?id=1821324
https://bugzilla.redhat.com/show_bug.cgi?id=1821271

Those are the only abrt bugzilla I have saved and in all cases, it didn't work.

**Comment by ernestask** [comment]
https://github.com/abrt/abrt/pull/1448 should take care of the side note issue. We’ll do a release soon-ish.

**Comment by ernestask** [comment]
Ah, so after piecing together some more information, it seems that, on the Fedora side, it’s members of the `fedorabugs` FAS group that get automagically added to `fedora_contrib` on Bugzilla. So it really is best to continue this discussion on Bugzilla. I can create a bug on Monday and then I will link it here and close this issue.

**Comment by ernestask** [comment]
Created https://bugzilla.redhat.com/show_bug.cgi?id=1825819. Closing for now, because I am not sure if there is anything actionable on our side.

**Comment by hroncok** [comment]
Thank you @ernestask for opening that bugzilla. I agree that there is nothing actionable form your side.

**Comment by kergon** [comment]
Another fix would be to work out what would need to change so it can add all the attachments at once instead of them appearing as separate updates.

**Comment by ernestask** [comment]
> Another fix would be to work out what would need to change so it can add all the attachments at once instead of them appearing as separate updates.

The only thing that *can* change is the WebService API. I noticed an existing request (though still downstream): https://bugzilla.redhat.com/show_bug.cgi?id=1173430.
