### ISSUE TITLE
RFE: attach /tmp/anaconda* files for Anaconda crashes

### ISSUE THREAD

**Issue by mschwendt** [abrt/libreport#621]
At https://bugzilla.redhat.com/1233177, an Anaconda developers complained about this:

> In the future, please attach the logs from /tmp to anaconda bugs, in particular
> the /tmp/anaconda-tb\* file containing the full traceback data. The files you
> attached contain no useful information.

It was ABRT that attached those files. ABRT could be taught to attach the requested files.

**Comment by xsuchy** [comment]
This should work nowadays. If you disagree, please reopen.
