### ISSUE TITLE
Drop subscription-manager-rhsm from spec

### ISSUE THREAD

**Issue by mkutlak** [abrt/libreport#688]
Libreport (**on** and **for** RHEL/CentOS 8/9) still requires `python3-subscription-manager-rhsm` but anything that used it was dropped in https://github.com/abrt/libreport/pull/637

See `libreport.spec` and `libreport.spec.in`:
https://github.com/abrt/libreport/blob/a65525dd5a35f00edc5aa3ca04ba5d55324c5c56/libreport.spec#L226

**Comment by michalfabik** [comment]
What do you mean by "**on** and **for** RHEL/CentOS 8/9"? The way you're stressing it makes it look like there's an important distinction that I seem to be missing.

**Comment by mkutlak** [comment]
The distinction is not important. I just wanted to point out that it is still used on RHEL/CentOS and it will be used in (for) future releases.
