### ISSUE TITLE
Incorrect user configuration path computation in reporter_bugzilla.py 

### ISSUE THREAD

**Issue by ydroneaud** [abrt/libreport#782]
Python reporter-bugzilla fails to access `~/.config/libreport/bugzilla.conf` because `os.path.join()` discards the result of `os.environ['HOME']` as `USER_HOME_CONFIG_PATH` starts with a `/` (and `os.path.join()` assumes it's an absolute path).

Reported as [bug #2175415](https://bugzilla.redhat.com/show_bug.cgi?id=2175415) on Fedora.

**Comment by msrb** [comment]
Thank you for spotting this ;)
