### ISSUE TITLE
sensitive words ignore list: XDG_ACTIVATION_TOKEN

### ISSUE THREAD

**Issue by kparal** [abrt/libreport#785]
Some bugs are marked as sensitive just because I have some `XDG_ACTIVATION_TOKEN` variable in `environ`. It matches on "token". I'm not sure what the variable is and whether it is really sensitive. Somebody more knowledgeable needs to check. But the same value is also listed in `DESKTOP_STARTUP_ID` and libreport doesn't mark it as sensitive. Perhaps `XDG_ACTIVATION_TOKEN` could be added to an ignore list to avoid too many private bug reports?

![libreport](https://user-images.githubusercontent.com/755451/225895521-c2bd26de-6564-497b-a7e3-9b93c947ae3c.png)

```
libreport-2.17.8-1.fc38.x86_64
```

**Comment by mgrabovsky** [comment]
Reading the related [Wayland documentation](https://wayland.app/protocols/xdg-activation-v1), the activation token is used in a "Protocol for requesting activation of surfaces". It appears as though the token is ephemeral and relevant only within a desktop session, so it should be safe to ignore.

Still, I'd appreciate a more informed opinion before making the decision.

**Comment by msrb** [comment]
This was fixed quite a long time ago in https://github.com/abrt/libreport/commit/7209784cb3d289bc72c51a33398d6fafc74021a0.
