### ISSUE TITLE
Error while installing libreport

### ISSUE THREAD

**Issue by Av1nag** [abrt/libreport#800]
while i'm trying to install i'm facing an error that is related to `libxml2` package

>[Avinag@ArchGNULinux libreport-master]$ make
make  all-recursive
make[1]: Entering directory '/home/Avinag/Downloads/libreport-master'
Making all in data
make[2]: Entering directory '/home/Avinag/Downloads/libreport-master/data'
Making all in augeas
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/data/augeas'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/data/augeas'
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/data'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/data'
make[2]: Leaving directory '/home/Avinag/Downloads/libreport-master/data'
Making all in po
make[2]: Entering directory '/home/Avinag/Downloads/libreport-master/po'
grep: warning: stray \ before #
grep: warning: stray \ before #
grep: warning: stray \ before #
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/Avinag/Downloads/libreport-master/po'
Making all in src
make[2]: Entering directory '/home/Avinag/Downloads/libreport-master/src'
Making all in include
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/src/include'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/include'
Making all in lib
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/src/lib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/lib'
Making all in report-python
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/src/report-python'
Making all in report
make[4]: Entering directory '/home/Avinag/Downloads/libreport-master/src/report-python/report'
ln -sf /home/Avinag/Downloads/libreport-master/src/report-python/report/.libs/_py3report.so ./
make[4]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/report-python/report'
make[4]: Entering directory '/home/Avinag/Downloads/libreport-master/src/report-python'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/report-python'
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/report-python'
Making all in cli
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/src/cli'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/cli'
Making all in client-python
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/src/client-python'
Making all in reportclient
make[4]: Entering directory '/home/Avinag/Downloads/libreport-master/src/client-python/reportclient'
Making all in internal
make[5]: Entering directory '/home/Avinag/Downloads/libreport-master/src/client-python/reportclient/internal'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/client-python/reportclient/internal'
make[5]: Entering directory '/home/Avinag/Downloads/libreport-master/src/client-python/reportclient'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/client-python/reportclient'
make[4]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/client-python/reportclient'
make[4]: Entering directory '/home/Avinag/Downloads/libreport-master/src/client-python'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/client-python'
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/client-python'
Making all in plugins
make[3]: Entering directory '/home/Avinag/Downloads/libreport-master/src/plugins'
Making all in python
make[4]: Entering directory '/home/Avinag/Downloads/libreport-master/src/plugins/python'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/plugins/python'
make[4]: Entering directory '/home/Avinag/Downloads/libreport-master/src/plugins'
  CC       reporter_mantisbt-reporter-mantisbt.o
In file included from reporter-mantisbt.c:22:
mantisbt.h:49:5: error: unknown type name ‘xmlNodePtr’
   49 |     xmlNodePtr sr_root;
      |     ^~~~~~~~~~
mantisbt.h:50:5: error: unknown type name ‘xmlNodePtr’
   50 |     xmlNodePtr sr_body;
      |     ^~~~~~~~~~
mantisbt.h:51:5: error: unknown type name ‘xmlNodePtr’
   51 |     xmlNodePtr sr_method;
      |     ^~~~~~~~~~
make[4]: *** [Makefile:1038: reporter_mantisbt-reporter-mantisbt.o] Error 1
make[4]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/plugins'
make[3]: *** [Makefile:1239: all-recursive] Error 1
make[3]: Leaving directory '/home/Avinag/Downloads/libreport-master/src/plugins'
make[2]: *** [Makefile:461: all-recursive] Error 1
make[2]: Leaving directory '/home/Avinag/Downloads/libreport-master/src'
make[1]: *** [Makefile:574: all-recursive] Error 1
make[1]: Leaving directory '/home/Avinag/Downloads/libreport-master'
make: *** [Makefile:481: all] Error 2

Also i've checked the `libxml2` directory but there is no file named `xmlNodePtr`

here's the `libxml2` directory 

> [Avinag@ArchGNULinux ~]$ cd /usr/include/libxml2/libxml
[Avinag@ArchGNULinux libxml]$ ls
HTMLparser.h  catalog.h   entities.h  nanohttp.h	 schemasInternals.h  valid.h	    xmlerror.h	  xmlregexp.h	     xmlunicode.h      xpointer.h
HTMLtree.h    chvalid.h   globals.h   parser.h		 schematron.h	     xinclude.h     xmlexports.h  xmlsave.h	     xmlversion.h
SAX.h	      debugXML.h  hash.h      parserInternals.h  threads.h	     xlink.h	    xmlmemory.h   xmlschemas.h	     xmlwriter.h
SAX2.h	      dict.h	  list.h      pattern.h		 tree.h		     xmlIO.h	    xmlmodule.h   xmlschemastypes.h  xpath.h
c14n.h	      encoding.h  nanoftp.h   relaxng.h		 uri.h		     xmlautomata.h  xmlreader.h   xmlstring.h	     xpathInternals.h

could you please help me to resolve the issue... please try to give the dev team support if possible..

**Comment by msrb** [comment]
Fixed in https://github.com/abrt/libreport/pull/801.
